export const HIGH_FIDELITY_CAPTURE = {
  detectIntervalMs: 33,
  emitIntervalMs: 24,
  width: 960,
  height: 720,
  frameRate: 30,
};

export const STABILITY_TUNING = {
  blendshapeDeadzone: 0.01,
  mouthBlendshapeDeadzone: 0.015,
  headDeadzone: 0.012,
  gazeDeadzone: 0.008,
  proximityDeadzone: 0.02,
};

export const DIGITAL_TWIN_TUNING = {
  headPitchSign: 1,
  headYawSign: -1,
  headRollSign: -1,
  headPitchGain: 1,
  headYawGain: 1.45,
  headRollGain: 1,
  headYawClamp: 1.15,
  gazeYawSign: -1,
  gazePitchSign: 1,
};

export const MOUTH_BLENDSHAPE_KEYS = new Set([
  'jawOpen',
  'jawForward',
  'jawLeft',
  'jawRight',
  'mouthClose',
  'mouthLeft',
  'mouthRight',
  'mouthSmile_L',
  'mouthSmile_R',
  'mouthFrown_L',
  'mouthFrown_R',
  'mouthStretch_L',
  'mouthStretch_R',
  'mouthDimple_L',
  'mouthDimple_R',
  'mouthFunnel',
  'mouthPucker',
  'mouthPress_L',
  'mouthPress_R',
  'mouthRollLower',
  'mouthRollUpper',
  'mouthShrugLower',
  'mouthShrugUpper',
  'mouthLowerDown_L',
  'mouthLowerDown_R',
  'mouthUpperUp_L',
  'mouthUpperUp_R',
  'tongueOut',
]);

export const MICRODETAIL_CHANNELS: Partial<Record<string, number>> = {
  eyeBlink_L: 0.16,
  eyeBlink_R: 0.16,
  eyeSquint_L: 0.22,
  eyeSquint_R: 0.22,
  eyeWide_L: 0.18,
  eyeWide_R: 0.18,
  mouthPress_L: 0.26,
  mouthPress_R: 0.26,
  mouthDimple_L: 0.24,
  mouthDimple_R: 0.24,
  mouthStretch_L: 0.18,
  mouthStretch_R: 0.18,
  mouthShrugLower: 0.18,
  mouthShrugUpper: 0.18,
  browInnerUp: 0.22,
  browDown_L: 0.22,
  browDown_R: 0.22,
  browOuterUp_L: 0.2,
  browOuterUp_R: 0.2,
  cheekSquint_L: 0.18,
  cheekSquint_R: 0.18,
  noseSneer_L: 0.22,
  noseSneer_R: 0.22,
};

export const MOUTH_SOLVE_BLEND: Partial<Record<string, number>> = {
  jawOpen: 0.78,
  jawForward: 0.72,
  jawLeft: 0.74,
  jawRight: 0.74,
  mouthClose: 0.76,
  mouthLeft: 0.72,
  mouthRight: 0.72,
  mouthSmile_L: 0.82,
  mouthSmile_R: 0.82,
  mouthFrown_L: 0.76,
  mouthFrown_R: 0.76,
  mouthStretch_L: 0.84,
  mouthStretch_R: 0.84,
  mouthDimple_L: 0.72,
  mouthDimple_R: 0.72,
  mouthFunnel: 0.8,
  mouthPucker: 0.84,
  mouthPress_L: 0.68,
  mouthPress_R: 0.68,
  mouthRollLower: 0.52,
  mouthRollUpper: 0.58,
  mouthShrugLower: 0.46,
  mouthShrugUpper: 0.48,
  mouthLowerDown_L: 0.28,
  mouthLowerDown_R: 0.28,
  mouthUpperUp_L: 0.32,
  mouthUpperUp_R: 0.32,
  tongueOut: 0.7,
};
